[[msolve]]
arch = "aarch64"
git-tree-sha1 = "aaac3d371fb97120deef8f3ab36e415b6d81c167"
march = "apple_m1"
os = "macos"

    [[msolve.download]]
    sha256 = "35df079197c438c39dcf41b0ed87478291037ed5c826e9dbfb4b824208d92585"
    url = "https://github.com/JuliaBinaryWrappers/msolve_jll.jl/releases/download/msolve-v0.900.501+0/msolve.v0.900.501.aarch64-apple-darwin-march+apple_m1.tar.gz"
[[msolve]]
arch = "aarch64"
git-tree-sha1 = "659e6bae5983d65e38174b3f2c8a72b4bc9677fc"
march = "armv8_0"
os = "macos"

    [[msolve.download]]
    sha256 = "7f159d7f642b35dc5b090520bd76f16f8bc0a7e0973eebf4a61baf1a8a9871c1"
    url = "https://github.com/JuliaBinaryWrappers/msolve_jll.jl/releases/download/msolve-v0.900.501+0/msolve.v0.900.501.aarch64-apple-darwin-march+armv8_0.tar.gz"
[[msolve]]
arch = "aarch64"
git-tree-sha1 = "7e7e106c6879eb9694adce90415f454ca0d6ade8"
libc = "glibc"
march = "a64fx"
os = "linux"

    [[msolve.download]]
    sha256 = "8616d546e538e4b97bb4b14ad8506fd9a9b44bcb7e45c3898a182884ba9acbc2"
    url = "https://github.com/JuliaBinaryWrappers/msolve_jll.jl/releases/download/msolve-v0.900.501+0/msolve.v0.900.501.aarch64-linux-gnu-march+a64fx.tar.gz"
[[msolve]]
arch = "aarch64"
git-tree-sha1 = "9d512247808882a092d0f475b40ed7ba13159c36"
libc = "glibc"
march = "armv8_0"
os = "linux"

    [[msolve.download]]
    sha256 = "d6643eaafa156c1e5d1fa105b329c33046e4bf164794d4c244319b22ebb6f366"
    url = "https://github.com/JuliaBinaryWrappers/msolve_jll.jl/releases/download/msolve-v0.900.501+0/msolve.v0.900.501.aarch64-linux-gnu-march+armv8_0.tar.gz"
[[msolve]]
arch = "aarch64"
git-tree-sha1 = "b2a7f8ec7248f407ca3218581922b17efb6d0cc5"
libc = "glibc"
march = "armv8_1"
os = "linux"

    [[msolve.download]]
    sha256 = "860fba8b0b4475ae85f1281ed101405b4dc89a04e2267ed1b3dbf54d7da527ac"
    url = "https://github.com/JuliaBinaryWrappers/msolve_jll.jl/releases/download/msolve-v0.900.501+0/msolve.v0.900.501.aarch64-linux-gnu-march+armv8_1.tar.gz"
[[msolve]]
arch = "aarch64"
git-tree-sha1 = "baecc3e17b233f5dd1e2d577ec39dcb675befdc9"
libc = "glibc"
march = "armv8_2_crypto"
os = "linux"

    [[msolve.download]]
    sha256 = "c21aa8ffbbc832cc63042a1abd18c9813547f5bb18247e93d980a75c8b5c3176"
    url = "https://github.com/JuliaBinaryWrappers/msolve_jll.jl/releases/download/msolve-v0.900.501+0/msolve.v0.900.501.aarch64-linux-gnu-march+armv8_2_crypto.tar.gz"
[[msolve]]
arch = "aarch64"
git-tree-sha1 = "a617bfbce6a6adf929cead64e1d526e902940afa"
libc = "musl"
march = "armv8_0"
os = "linux"

    [[msolve.download]]
    sha256 = "072691b244cf24f94dba8753a0c1ad89f5ab017ed56e510fa9b98148ab176668"
    url = "https://github.com/JuliaBinaryWrappers/msolve_jll.jl/releases/download/msolve-v0.900.501+0/msolve.v0.900.501.aarch64-linux-musl-march+armv8_0.tar.gz"
[[msolve]]
arch = "aarch64"
git-tree-sha1 = "65fed212623e8fdc9c73e0b75ddd9c5f523bbd6e"
libc = "musl"
march = "armv8_1"
os = "linux"

    [[msolve.download]]
    sha256 = "4e319cb1bd82f97d8941fd3d8bb73fd5746d9f03481f84311e21927868d1185f"
    url = "https://github.com/JuliaBinaryWrappers/msolve_jll.jl/releases/download/msolve-v0.900.501+0/msolve.v0.900.501.aarch64-linux-musl-march+armv8_1.tar.gz"
[[msolve]]
arch = "aarch64"
git-tree-sha1 = "a6ed63b0e9541aab0e4d464bcf43b17760c899df"
libc = "musl"
march = "armv8_2_crypto"
os = "linux"

    [[msolve.download]]
    sha256 = "f8a221bc0106e91862f04f33db40d575cd66c76f59b8ecbc0faffd5ab81a7ae2"
    url = "https://github.com/JuliaBinaryWrappers/msolve_jll.jl/releases/download/msolve-v0.900.501+0/msolve.v0.900.501.aarch64-linux-musl-march+armv8_2_crypto.tar.gz"
[[msolve]]
arch = "aarch64"
git-tree-sha1 = "766fd2a1a7a98e0fa0df30d738f6408b6a8e6ec5"
march = "armv8_0"
os = "freebsd"

    [[msolve.download]]
    sha256 = "5315bdb29621ec67068fb0e0c0315262f5e3299b9b7012ef1599624b02be05a0"
    url = "https://github.com/JuliaBinaryWrappers/msolve_jll.jl/releases/download/msolve-v0.900.501+0/msolve.v0.900.501.aarch64-unknown-freebsd-march+armv8_0.tar.gz"
[[msolve]]
arch = "aarch64"
git-tree-sha1 = "49a0c1a26e1941b6855765dedf35faa037672dbd"
march = "armv8_1"
os = "freebsd"

    [[msolve.download]]
    sha256 = "61d19a0821f130c5d608d779a086a7d8cb4afa10e84ac5fa3ddd7ab5bee05ede"
    url = "https://github.com/JuliaBinaryWrappers/msolve_jll.jl/releases/download/msolve-v0.900.501+0/msolve.v0.900.501.aarch64-unknown-freebsd-march+armv8_1.tar.gz"
[[msolve]]
arch = "aarch64"
git-tree-sha1 = "ad314b8eaeafca63dbf1415c695091ddcd59bb29"
march = "armv8_2_crypto"
os = "freebsd"

    [[msolve.download]]
    sha256 = "1565032342b885af455c97608f4fd285ee3b8076acd0281ab892800c48aa6b4f"
    url = "https://github.com/JuliaBinaryWrappers/msolve_jll.jl/releases/download/msolve-v0.900.501+0/msolve.v0.900.501.aarch64-unknown-freebsd-march+armv8_2_crypto.tar.gz"
[[msolve]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "a5d5ac641f0f2a22d4a01bd2c4c26c954d888cc4"
libc = "glibc"
march = "arm1176jzfs"
os = "linux"

    [[msolve.download]]
    sha256 = "79aa9bf0d957e6a7c1e283a70ca52c8a908427055cb50b54aa3e003d43ee02dc"
    url = "https://github.com/JuliaBinaryWrappers/msolve_jll.jl/releases/download/msolve-v0.900.501+0/msolve.v0.900.501.armv6l-linux-gnueabihf-march+arm1176jzfs.tar.gz"
[[msolve]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "ffdc8a3a66188afcc5eecbd452ff0f134afb3e63"
libc = "musl"
march = "arm1176jzfs"
os = "linux"

    [[msolve.download]]
    sha256 = "c59b23e269dd735bae910c3587f879a7b93dc4c1ac0288ea4fcd4aa6c8d98a09"
    url = "https://github.com/JuliaBinaryWrappers/msolve_jll.jl/releases/download/msolve-v0.900.501+0/msolve.v0.900.501.armv6l-linux-musleabihf-march+arm1176jzfs.tar.gz"
[[msolve]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "1a56a80d59204a6cb31bde47f040a15873ca64ea"
libc = "glibc"
march = "armv7l"
os = "linux"

    [[msolve.download]]
    sha256 = "361627a3fe53f34c25a0522cec969bf6dfba3f5935dc907b2ea2f5cb7460516f"
    url = "https://github.com/JuliaBinaryWrappers/msolve_jll.jl/releases/download/msolve-v0.900.501+0/msolve.v0.900.501.armv7l-linux-gnueabihf-march+armv7l.tar.gz"
[[msolve]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "a9e88f5484bcf1f1538fe5b465d0fce0ceb2e418"
libc = "glibc"
march = "neonvfpv4"
os = "linux"

    [[msolve.download]]
    sha256 = "818bdb79e0ff273602e1043843fe2f5ff755d00f760698b20ea4a313214dabbd"
    url = "https://github.com/JuliaBinaryWrappers/msolve_jll.jl/releases/download/msolve-v0.900.501+0/msolve.v0.900.501.armv7l-linux-gnueabihf-march+neonvfpv4.tar.gz"
[[msolve]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "a43e68eb15f5ab014619ae91455f5fb1b1b1ca7a"
libc = "musl"
march = "armv7l"
os = "linux"

    [[msolve.download]]
    sha256 = "7f2d4d011ff068caa8406f661ce75cb47beb969b28ea518f5faa9f6372a3ae35"
    url = "https://github.com/JuliaBinaryWrappers/msolve_jll.jl/releases/download/msolve-v0.900.501+0/msolve.v0.900.501.armv7l-linux-musleabihf-march+armv7l.tar.gz"
[[msolve]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "fa6fd156dc35f5c3fa32a47db8b147339d51629a"
libc = "musl"
march = "neonvfpv4"
os = "linux"

    [[msolve.download]]
    sha256 = "6b7188b411f8b5c72839a3bf40af674f5dea0c074a84ea232aa1d81adb465c1e"
    url = "https://github.com/JuliaBinaryWrappers/msolve_jll.jl/releases/download/msolve-v0.900.501+0/msolve.v0.900.501.armv7l-linux-musleabihf-march+neonvfpv4.tar.gz"
[[msolve]]
arch = "i686"
git-tree-sha1 = "c051f5845860bfc96725e0c5fc5abe81f4aecdd1"
libc = "glibc"
march = "pentium4"
os = "linux"

    [[msolve.download]]
    sha256 = "8da2adf0638547d5860320c5bfa8f69f4aa3c82eb14a23a8ed9317d2849812ee"
    url = "https://github.com/JuliaBinaryWrappers/msolve_jll.jl/releases/download/msolve-v0.900.501+0/msolve.v0.900.501.i686-linux-gnu-march+pentium4.tar.gz"
[[msolve]]
arch = "i686"
git-tree-sha1 = "5c999e51cd21e77d5d6e515f26f6a5ba1dcc8b79"
libc = "glibc"
march = "prescott"
os = "linux"

    [[msolve.download]]
    sha256 = "1e724cf90baf3bb231a7c2752508120538989925e6d07e9d82254bd3dda644db"
    url = "https://github.com/JuliaBinaryWrappers/msolve_jll.jl/releases/download/msolve-v0.900.501+0/msolve.v0.900.501.i686-linux-gnu-march+prescott.tar.gz"
[[msolve]]
arch = "i686"
git-tree-sha1 = "f3e2a4289fdd7bbf377c595f7ed87a115fbe9c32"
libc = "musl"
march = "pentium4"
os = "linux"

    [[msolve.download]]
    sha256 = "f2a7334a4e028aa9b21b867dcdba151e4c89bb3bd40e8291373c8bff4a42d9b0"
    url = "https://github.com/JuliaBinaryWrappers/msolve_jll.jl/releases/download/msolve-v0.900.501+0/msolve.v0.900.501.i686-linux-musl-march+pentium4.tar.gz"
[[msolve]]
arch = "i686"
git-tree-sha1 = "517b32e4ecb8667ad3b32c3d695d5f3cc41893ff"
libc = "musl"
march = "prescott"
os = "linux"

    [[msolve.download]]
    sha256 = "b62e6db0975101d7799d798c66ec2593768e88f25438912ca5670acf1c2b0eee"
    url = "https://github.com/JuliaBinaryWrappers/msolve_jll.jl/releases/download/msolve-v0.900.501+0/msolve.v0.900.501.i686-linux-musl-march+prescott.tar.gz"
[[msolve]]
arch = "powerpc64le"
git-tree-sha1 = "ac0dc63bca1708648f15c343e3c1ae8613531fad"
libc = "glibc"
march = "power8"
os = "linux"

    [[msolve.download]]
    sha256 = "709b56146bb52d28e70d62a8435d7801ce9a788482aefd07f8091764e7f512d2"
    url = "https://github.com/JuliaBinaryWrappers/msolve_jll.jl/releases/download/msolve-v0.900.501+0/msolve.v0.900.501.powerpc64le-linux-gnu-march+power8.tar.gz"
[[msolve]]
arch = "riscv64"
git-tree-sha1 = "75c187c06a5c03ba709ef768198b98c766568a06"
libc = "glibc"
march = "riscv64"
os = "linux"

    [[msolve.download]]
    sha256 = "2f04107057ba6577780571f2429fe5647a9f35b3edc18312c6181b7937ec9d93"
    url = "https://github.com/JuliaBinaryWrappers/msolve_jll.jl/releases/download/msolve-v0.900.501+0/msolve.v0.900.501.riscv64-linux-gnu-march+riscv64.tar.gz"
[[msolve]]
arch = "x86_64"
git-tree-sha1 = "272e7ffcd01be347a74f9169ef8e8fc308faab66"
march = "avx"
os = "macos"

    [[msolve.download]]
    sha256 = "c22b58ca7aba09c4870922cf4baf05bcdf2a0e1f708e67a8ddfbd71eb92d7e39"
    url = "https://github.com/JuliaBinaryWrappers/msolve_jll.jl/releases/download/msolve-v0.900.501+0/msolve.v0.900.501.x86_64-apple-darwin-march+avx.tar.gz"
[[msolve]]
arch = "x86_64"
git-tree-sha1 = "55042eb0eb8e77081d065929a451121e11346694"
march = "avx2"
os = "macos"

    [[msolve.download]]
    sha256 = "c220fef9aae0b54f564eddc1ba313afd8da869a9c948eeadfef767c13c2570ba"
    url = "https://github.com/JuliaBinaryWrappers/msolve_jll.jl/releases/download/msolve-v0.900.501+0/msolve.v0.900.501.x86_64-apple-darwin-march+avx2.tar.gz"
[[msolve]]
arch = "x86_64"
git-tree-sha1 = "66afbcd56765283909a782f94967e877cf8b1d03"
march = "avx512"
os = "macos"

    [[msolve.download]]
    sha256 = "ae308bf32ce8d9a1fb8dac65f202740d9b2adce1beb84f47f62652c1c5c909ba"
    url = "https://github.com/JuliaBinaryWrappers/msolve_jll.jl/releases/download/msolve-v0.900.501+0/msolve.v0.900.501.x86_64-apple-darwin-march+avx512.tar.gz"
[[msolve]]
arch = "x86_64"
git-tree-sha1 = "aa0ab387c7310b7078f954beff73d5006c5c1fc1"
march = "x86_64"
os = "macos"

    [[msolve.download]]
    sha256 = "0cd4b4a6854583379f90c99b8f3ba557f0c9bdce5f29c7ae91e4307b2ff6e8a4"
    url = "https://github.com/JuliaBinaryWrappers/msolve_jll.jl/releases/download/msolve-v0.900.501+0/msolve.v0.900.501.x86_64-apple-darwin-march+x86_64.tar.gz"
[[msolve]]
arch = "x86_64"
git-tree-sha1 = "7ee5ffed770e4fb6bc21d418be688f20b5cd003f"
libc = "glibc"
march = "avx"
os = "linux"

    [[msolve.download]]
    sha256 = "d2fcc3547cd7e5caf456822b22d1a7da112c292fac82f46e1cf5af1534413288"
    url = "https://github.com/JuliaBinaryWrappers/msolve_jll.jl/releases/download/msolve-v0.900.501+0/msolve.v0.900.501.x86_64-linux-gnu-march+avx.tar.gz"
[[msolve]]
arch = "x86_64"
git-tree-sha1 = "1812c6022cc3010a89a4a76f1233e7156e4eedbc"
libc = "glibc"
march = "avx2"
os = "linux"

    [[msolve.download]]
    sha256 = "ccc09254e528ed41edac1b60ceb6ea4cff95e3559d4f395441d8671e73abdfc8"
    url = "https://github.com/JuliaBinaryWrappers/msolve_jll.jl/releases/download/msolve-v0.900.501+0/msolve.v0.900.501.x86_64-linux-gnu-march+avx2.tar.gz"
[[msolve]]
arch = "x86_64"
git-tree-sha1 = "1bc16b7e10b755e72c7b6272d1cd3ffd16498430"
libc = "glibc"
march = "avx512"
os = "linux"

    [[msolve.download]]
    sha256 = "84857d687181042d6e0a603a91d85abf4c3de77ad56f4f68dd8a6ee034411dbc"
    url = "https://github.com/JuliaBinaryWrappers/msolve_jll.jl/releases/download/msolve-v0.900.501+0/msolve.v0.900.501.x86_64-linux-gnu-march+avx512.tar.gz"
[[msolve]]
arch = "x86_64"
git-tree-sha1 = "f42a91497a06884bcbab3022ddf50c9411519e25"
libc = "glibc"
march = "x86_64"
os = "linux"

    [[msolve.download]]
    sha256 = "ffbc22e6db754eb7f9fd23142fba354e6f967c2fb0bbd9f18a880fd97c9d302a"
    url = "https://github.com/JuliaBinaryWrappers/msolve_jll.jl/releases/download/msolve-v0.900.501+0/msolve.v0.900.501.x86_64-linux-gnu-march+x86_64.tar.gz"
[[msolve]]
arch = "x86_64"
git-tree-sha1 = "4a11793cedb88afdc36ace1122fe603fafa34846"
libc = "musl"
march = "avx"
os = "linux"

    [[msolve.download]]
    sha256 = "db40bcacefe3740549a8145f8a4aa373574ef8586cd9efb1502c88c40d3275e8"
    url = "https://github.com/JuliaBinaryWrappers/msolve_jll.jl/releases/download/msolve-v0.900.501+0/msolve.v0.900.501.x86_64-linux-musl-march+avx.tar.gz"
[[msolve]]
arch = "x86_64"
git-tree-sha1 = "c337cffbbe2de768f0a15b6ef7b2eb630f178fa3"
libc = "musl"
march = "avx2"
os = "linux"

    [[msolve.download]]
    sha256 = "d2196914b3097334844a110afaf6d21ae011cd1d51da5afa3a9b136f039926c5"
    url = "https://github.com/JuliaBinaryWrappers/msolve_jll.jl/releases/download/msolve-v0.900.501+0/msolve.v0.900.501.x86_64-linux-musl-march+avx2.tar.gz"
[[msolve]]
arch = "x86_64"
git-tree-sha1 = "2a45a1c9aa31fa6b1dc7d7de5cdc55ac69e1fefc"
libc = "musl"
march = "avx512"
os = "linux"

    [[msolve.download]]
    sha256 = "d8f03a5b89f0bd10bd729757e37130ea5bad9ff5bcbd04c21151d2c603b51f71"
    url = "https://github.com/JuliaBinaryWrappers/msolve_jll.jl/releases/download/msolve-v0.900.501+0/msolve.v0.900.501.x86_64-linux-musl-march+avx512.tar.gz"
[[msolve]]
arch = "x86_64"
git-tree-sha1 = "b544413128d0bc1770d19f8b72db4d5fdb046438"
libc = "musl"
march = "x86_64"
os = "linux"

    [[msolve.download]]
    sha256 = "149a533693c1694461d51c36e289e27efcb6837519f985b125d62321a1fa3476"
    url = "https://github.com/JuliaBinaryWrappers/msolve_jll.jl/releases/download/msolve-v0.900.501+0/msolve.v0.900.501.x86_64-linux-musl-march+x86_64.tar.gz"
[[msolve]]
arch = "x86_64"
git-tree-sha1 = "f6ca3046bb131d59f0a73139cf40f4598108089a"
march = "avx"
os = "freebsd"

    [[msolve.download]]
    sha256 = "31d3b53514956ca66ce3017c0e0203dee57ad7e8fda989a45016eecb6ff64ede"
    url = "https://github.com/JuliaBinaryWrappers/msolve_jll.jl/releases/download/msolve-v0.900.501+0/msolve.v0.900.501.x86_64-unknown-freebsd-march+avx.tar.gz"
[[msolve]]
arch = "x86_64"
git-tree-sha1 = "c46c9980efe0a458c1afab71fe639b24de02a5ea"
march = "avx2"
os = "freebsd"

    [[msolve.download]]
    sha256 = "b29b91d6534bb85ed94d21109c795c01f3163ed5049c70a1c13a08c10d4f5596"
    url = "https://github.com/JuliaBinaryWrappers/msolve_jll.jl/releases/download/msolve-v0.900.501+0/msolve.v0.900.501.x86_64-unknown-freebsd-march+avx2.tar.gz"
[[msolve]]
arch = "x86_64"
git-tree-sha1 = "ca08d6a01771ca169092b1d094bd3bc120820205"
march = "avx512"
os = "freebsd"

    [[msolve.download]]
    sha256 = "0241b300a17ea9793e8ad60cc91022260be4b47d86ed792fa73db3c25456f44c"
    url = "https://github.com/JuliaBinaryWrappers/msolve_jll.jl/releases/download/msolve-v0.900.501+0/msolve.v0.900.501.x86_64-unknown-freebsd-march+avx512.tar.gz"
[[msolve]]
arch = "x86_64"
git-tree-sha1 = "3cdd1e8341ece96c674d22e35ff42c52d232d8a8"
march = "x86_64"
os = "freebsd"

    [[msolve.download]]
    sha256 = "3ca40cb5be6e316ef41888a8f96d36465a88f6105d431ae46296a36d7ce001b1"
    url = "https://github.com/JuliaBinaryWrappers/msolve_jll.jl/releases/download/msolve-v0.900.501+0/msolve.v0.900.501.x86_64-unknown-freebsd-march+x86_64.tar.gz"
