[[msolve]]
arch = "aarch64"
git-tree-sha1 = "2f1b530e494f620a7d1bfbbed3356b2d6ffedddc"
march = "apple_m1"
os = "macos"

    [[msolve.download]]
    sha256 = "2a23827f64c9d7f2b1cba8d228eadec6dbf75eb8e0234bce0cd416bd558d4418"
    url = "https://github.com/JuliaBinaryWrappers/msolve_jll.jl/releases/download/msolve-v0.900.500+0/msolve.v0.900.500.aarch64-apple-darwin-march+apple_m1.tar.gz"
[[msolve]]
arch = "aarch64"
git-tree-sha1 = "0ff3fa376c7a28d57199549740a69b19f92664ec"
march = "armv8_0"
os = "macos"

    [[msolve.download]]
    sha256 = "65a91baf50f2577ec3c07af28ec11e2331449631db5d41f5715db3e4d0f5a911"
    url = "https://github.com/JuliaBinaryWrappers/msolve_jll.jl/releases/download/msolve-v0.900.500+0/msolve.v0.900.500.aarch64-apple-darwin-march+armv8_0.tar.gz"
[[msolve]]
arch = "aarch64"
git-tree-sha1 = "fcbcf1fcff6e328c3ac1df74d0f8c72d7f4c35d1"
libc = "glibc"
march = "a64fx"
os = "linux"

    [[msolve.download]]
    sha256 = "01fc8ce74314bde8b793b3e43b954cd0803bcd619aa3e5e72ec57d3ff48d1673"
    url = "https://github.com/JuliaBinaryWrappers/msolve_jll.jl/releases/download/msolve-v0.900.500+0/msolve.v0.900.500.aarch64-linux-gnu-march+a64fx.tar.gz"
[[msolve]]
arch = "aarch64"
git-tree-sha1 = "020e6b63df45da2e2dc5a853ca81a62f24d579e2"
libc = "glibc"
march = "armv8_0"
os = "linux"

    [[msolve.download]]
    sha256 = "879032af7257644c4810049530400c4b0e44ca8a91ac818a5d1bd616a850ae00"
    url = "https://github.com/JuliaBinaryWrappers/msolve_jll.jl/releases/download/msolve-v0.900.500+0/msolve.v0.900.500.aarch64-linux-gnu-march+armv8_0.tar.gz"
[[msolve]]
arch = "aarch64"
git-tree-sha1 = "ef2a11ec286691ec5194144bac4dc314c11c4b1a"
libc = "glibc"
march = "armv8_1"
os = "linux"

    [[msolve.download]]
    sha256 = "11ec02f02ac2b0d9178bb4ff979b4d30be837aa12ec31e6849f4fa84946d1c1b"
    url = "https://github.com/JuliaBinaryWrappers/msolve_jll.jl/releases/download/msolve-v0.900.500+0/msolve.v0.900.500.aarch64-linux-gnu-march+armv8_1.tar.gz"
[[msolve]]
arch = "aarch64"
git-tree-sha1 = "2944cb985e331a952cbe951b9a3bd79990a35385"
libc = "glibc"
march = "armv8_2_crypto"
os = "linux"

    [[msolve.download]]
    sha256 = "4ab9dbfe7904fff7921e61224bf8f47031f3f56b818f16ffa6e20cc91fb32fb0"
    url = "https://github.com/JuliaBinaryWrappers/msolve_jll.jl/releases/download/msolve-v0.900.500+0/msolve.v0.900.500.aarch64-linux-gnu-march+armv8_2_crypto.tar.gz"
[[msolve]]
arch = "aarch64"
git-tree-sha1 = "42fb4118defff2bc49e7fa791e2639424ed909e8"
libc = "musl"
march = "armv8_0"
os = "linux"

    [[msolve.download]]
    sha256 = "b15d5db6fef4c13ddf173c866672b8998529e298e208bb7917faed7f02e68e39"
    url = "https://github.com/JuliaBinaryWrappers/msolve_jll.jl/releases/download/msolve-v0.900.500+0/msolve.v0.900.500.aarch64-linux-musl-march+armv8_0.tar.gz"
[[msolve]]
arch = "aarch64"
git-tree-sha1 = "9ea8d424f81066c3f2e4ccd22f8c0066ac6606a0"
libc = "musl"
march = "armv8_1"
os = "linux"

    [[msolve.download]]
    sha256 = "9a1bc35a0ba8830d311ba78e1fa668b52353532d1c1f1df75ba03e5b73cd94cf"
    url = "https://github.com/JuliaBinaryWrappers/msolve_jll.jl/releases/download/msolve-v0.900.500+0/msolve.v0.900.500.aarch64-linux-musl-march+armv8_1.tar.gz"
[[msolve]]
arch = "aarch64"
git-tree-sha1 = "67a1edd8dba309d1b74976e92dbd01611273a986"
libc = "musl"
march = "armv8_2_crypto"
os = "linux"

    [[msolve.download]]
    sha256 = "bddf3541631ae3c2e929bab4da988876325e80ddbdac91ca687fb7bd99ff71f7"
    url = "https://github.com/JuliaBinaryWrappers/msolve_jll.jl/releases/download/msolve-v0.900.500+0/msolve.v0.900.500.aarch64-linux-musl-march+armv8_2_crypto.tar.gz"
[[msolve]]
arch = "aarch64"
git-tree-sha1 = "624e860c570f78f0536b325153df762045fb9690"
march = "armv8_0"
os = "freebsd"

    [[msolve.download]]
    sha256 = "6ceaa30505f255a3d19122d2b30ec282008a63c1f830e3a6dd74ac5432cc2231"
    url = "https://github.com/JuliaBinaryWrappers/msolve_jll.jl/releases/download/msolve-v0.900.500+0/msolve.v0.900.500.aarch64-unknown-freebsd-march+armv8_0.tar.gz"
[[msolve]]
arch = "aarch64"
git-tree-sha1 = "54b1f89c34a9483b2be6596736dd0993abe761b3"
march = "armv8_1"
os = "freebsd"

    [[msolve.download]]
    sha256 = "bd7f6f53a3c5faba550a3ca9465a7eda5ea7e5ef829b0e003013defa20598ab7"
    url = "https://github.com/JuliaBinaryWrappers/msolve_jll.jl/releases/download/msolve-v0.900.500+0/msolve.v0.900.500.aarch64-unknown-freebsd-march+armv8_1.tar.gz"
[[msolve]]
arch = "aarch64"
git-tree-sha1 = "a98919e58f9abe1def2ec2007a0d4861212fe988"
march = "armv8_2_crypto"
os = "freebsd"

    [[msolve.download]]
    sha256 = "0cb81bacc7d7d211dad8433bf941be6365da8724a71f316c97a95a0cde5250c0"
    url = "https://github.com/JuliaBinaryWrappers/msolve_jll.jl/releases/download/msolve-v0.900.500+0/msolve.v0.900.500.aarch64-unknown-freebsd-march+armv8_2_crypto.tar.gz"
[[msolve]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "dcb95b59800879833f6ba2d58c0e13bdeb6bc799"
libc = "glibc"
march = "arm1176jzfs"
os = "linux"

    [[msolve.download]]
    sha256 = "4825d009086f1564f7406bc3b84a0a54916ceeebe9694e2c0752e7f08d5910d1"
    url = "https://github.com/JuliaBinaryWrappers/msolve_jll.jl/releases/download/msolve-v0.900.500+0/msolve.v0.900.500.armv6l-linux-gnueabihf-march+arm1176jzfs.tar.gz"
[[msolve]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "9976759cb6935a6eb1a0d3b26e93832e3f6d3651"
libc = "musl"
march = "arm1176jzfs"
os = "linux"

    [[msolve.download]]
    sha256 = "a6af7090d9986f063144a4340fdcd2bb0ca585916e90922d48f0bee65ef048f9"
    url = "https://github.com/JuliaBinaryWrappers/msolve_jll.jl/releases/download/msolve-v0.900.500+0/msolve.v0.900.500.armv6l-linux-musleabihf-march+arm1176jzfs.tar.gz"
[[msolve]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "a8cd34c10ceb751897120b3de0f1eed2782f6cd4"
libc = "glibc"
march = "armv7l"
os = "linux"

    [[msolve.download]]
    sha256 = "81876868c74b54520cb95bf122e853ca4020e634efcd4ad13f0e0f5614d4e463"
    url = "https://github.com/JuliaBinaryWrappers/msolve_jll.jl/releases/download/msolve-v0.900.500+0/msolve.v0.900.500.armv7l-linux-gnueabihf-march+armv7l.tar.gz"
[[msolve]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "82d06b7eecb6184087abc4a10209331e9b91bc60"
libc = "glibc"
march = "neonvfpv4"
os = "linux"

    [[msolve.download]]
    sha256 = "7c80ce60920bebaf4d693e9419501d5c44dc9354ba66ce0d4124e6df66b194b4"
    url = "https://github.com/JuliaBinaryWrappers/msolve_jll.jl/releases/download/msolve-v0.900.500+0/msolve.v0.900.500.armv7l-linux-gnueabihf-march+neonvfpv4.tar.gz"
[[msolve]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "3ce812792df581b1b10ea807fbc60821a1f28bb5"
libc = "musl"
march = "armv7l"
os = "linux"

    [[msolve.download]]
    sha256 = "b95e9e071d96aa21f12fe3272e060955d31d31e47da941e065847dc44856e29f"
    url = "https://github.com/JuliaBinaryWrappers/msolve_jll.jl/releases/download/msolve-v0.900.500+0/msolve.v0.900.500.armv7l-linux-musleabihf-march+armv7l.tar.gz"
[[msolve]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "5c6bde809416f9a3192465105429b0c95a2d7d97"
libc = "musl"
march = "neonvfpv4"
os = "linux"

    [[msolve.download]]
    sha256 = "ac034c6d7dd986fec230011d7cd61ac310bff0ae6f75b9dc4bce7f5e41df9519"
    url = "https://github.com/JuliaBinaryWrappers/msolve_jll.jl/releases/download/msolve-v0.900.500+0/msolve.v0.900.500.armv7l-linux-musleabihf-march+neonvfpv4.tar.gz"
[[msolve]]
arch = "i686"
git-tree-sha1 = "297fffdb81680cf88996146474b0d21fe320f197"
libc = "glibc"
march = "pentium4"
os = "linux"

    [[msolve.download]]
    sha256 = "b2dff3233496881292b3bbdd5c381b0bc328e578a3e87c2a2b43d39ec60f00d7"
    url = "https://github.com/JuliaBinaryWrappers/msolve_jll.jl/releases/download/msolve-v0.900.500+0/msolve.v0.900.500.i686-linux-gnu-march+pentium4.tar.gz"
[[msolve]]
arch = "i686"
git-tree-sha1 = "bcc2dcab627a4edb0dcd3451d6267680ea1b44e5"
libc = "glibc"
march = "prescott"
os = "linux"

    [[msolve.download]]
    sha256 = "945b862e4d5a0859459115c05d04708de9f7f98e9a60e90b932aa25fe78b0e84"
    url = "https://github.com/JuliaBinaryWrappers/msolve_jll.jl/releases/download/msolve-v0.900.500+0/msolve.v0.900.500.i686-linux-gnu-march+prescott.tar.gz"
[[msolve]]
arch = "i686"
git-tree-sha1 = "3baa299c754031a9afe97bf98cc17918fe936e46"
libc = "musl"
march = "pentium4"
os = "linux"

    [[msolve.download]]
    sha256 = "e3df175ddec5aeae7317512e673e65a2075989dc086dda8bca95dae15c20fa6f"
    url = "https://github.com/JuliaBinaryWrappers/msolve_jll.jl/releases/download/msolve-v0.900.500+0/msolve.v0.900.500.i686-linux-musl-march+pentium4.tar.gz"
[[msolve]]
arch = "i686"
git-tree-sha1 = "0f1f1abcd549bd7c947e775a470eacc28ada3c98"
libc = "musl"
march = "prescott"
os = "linux"

    [[msolve.download]]
    sha256 = "adecc364837874bad3a96fd2e6c47d8686d693bc340aecd7eee5352b79651258"
    url = "https://github.com/JuliaBinaryWrappers/msolve_jll.jl/releases/download/msolve-v0.900.500+0/msolve.v0.900.500.i686-linux-musl-march+prescott.tar.gz"
[[msolve]]
arch = "powerpc64le"
git-tree-sha1 = "430ad94a74c6cb128846fc8ff9ef7b7b35927188"
libc = "glibc"
march = "power8"
os = "linux"

    [[msolve.download]]
    sha256 = "9ac571a205fba28704ab963d31faef969713e798a26eeba17b27861a2a479344"
    url = "https://github.com/JuliaBinaryWrappers/msolve_jll.jl/releases/download/msolve-v0.900.500+0/msolve.v0.900.500.powerpc64le-linux-gnu-march+power8.tar.gz"
[[msolve]]
arch = "riscv64"
git-tree-sha1 = "e9f0f139f20eb8c91daaa71ee2bfc59461fa7744"
libc = "glibc"
march = "riscv64"
os = "linux"

    [[msolve.download]]
    sha256 = "c2c08c47a0cf20f46d18168c617489f875b57a18ac2152f82d1c7a98c558e8e7"
    url = "https://github.com/JuliaBinaryWrappers/msolve_jll.jl/releases/download/msolve-v0.900.500+0/msolve.v0.900.500.riscv64-linux-gnu-march+riscv64.tar.gz"
[[msolve]]
arch = "x86_64"
git-tree-sha1 = "018a9f0d6cb462a67c11a8ea569088d0cbdb419a"
march = "avx"
os = "macos"

    [[msolve.download]]
    sha256 = "ea08afeea1cb29dc9c86a38b6e9226153207e8180d8ba1302b8f2ae0d0ec16e4"
    url = "https://github.com/JuliaBinaryWrappers/msolve_jll.jl/releases/download/msolve-v0.900.500+0/msolve.v0.900.500.x86_64-apple-darwin-march+avx.tar.gz"
[[msolve]]
arch = "x86_64"
git-tree-sha1 = "770026d556b8ee26caf3829c5e6fbb0844c9e96d"
march = "avx2"
os = "macos"

    [[msolve.download]]
    sha256 = "8ac0bca796a14974ad6b8e61e76033da2823239e631aa2310efe695c2c7610ff"
    url = "https://github.com/JuliaBinaryWrappers/msolve_jll.jl/releases/download/msolve-v0.900.500+0/msolve.v0.900.500.x86_64-apple-darwin-march+avx2.tar.gz"
[[msolve]]
arch = "x86_64"
git-tree-sha1 = "9dac639e6c618b56f28b027adf257da5d9242255"
march = "avx512"
os = "macos"

    [[msolve.download]]
    sha256 = "e7ab5731b0a9663f30a0d227baa4aa71db149ade87ee4c84b71c0fd43bef1e8c"
    url = "https://github.com/JuliaBinaryWrappers/msolve_jll.jl/releases/download/msolve-v0.900.500+0/msolve.v0.900.500.x86_64-apple-darwin-march+avx512.tar.gz"
[[msolve]]
arch = "x86_64"
git-tree-sha1 = "867ca4814099a57bf2d1969bf61a538a594ac725"
march = "x86_64"
os = "macos"

    [[msolve.download]]
    sha256 = "c997b1eb4688e93b749bc642e1dcee3384a3ba83ef8828d7a89fb5a1bf1a04ff"
    url = "https://github.com/JuliaBinaryWrappers/msolve_jll.jl/releases/download/msolve-v0.900.500+0/msolve.v0.900.500.x86_64-apple-darwin-march+x86_64.tar.gz"
[[msolve]]
arch = "x86_64"
git-tree-sha1 = "518ebbacb44c76dfbbdfc0a34906835fa547d7ba"
libc = "glibc"
march = "avx"
os = "linux"

    [[msolve.download]]
    sha256 = "55014a41d001451a624a3c16d03f040e4864fae87a4fd124cec45c6d752edce8"
    url = "https://github.com/JuliaBinaryWrappers/msolve_jll.jl/releases/download/msolve-v0.900.500+0/msolve.v0.900.500.x86_64-linux-gnu-march+avx.tar.gz"
[[msolve]]
arch = "x86_64"
git-tree-sha1 = "17e87192c7df688afa174ed13b4998ce8af3cde8"
libc = "glibc"
march = "avx2"
os = "linux"

    [[msolve.download]]
    sha256 = "3d9447546c59c0573af31bde21c0b065e45b18fd47849784990d895125ac4d89"
    url = "https://github.com/JuliaBinaryWrappers/msolve_jll.jl/releases/download/msolve-v0.900.500+0/msolve.v0.900.500.x86_64-linux-gnu-march+avx2.tar.gz"
[[msolve]]
arch = "x86_64"
git-tree-sha1 = "866db97e0599de6b65abe6d5d27eff50d45e2b77"
libc = "glibc"
march = "avx512"
os = "linux"

    [[msolve.download]]
    sha256 = "66820923958af1f7ca987f1a9e649448a4a8f0d6cdd2aa1aaf20f1e5c1408274"
    url = "https://github.com/JuliaBinaryWrappers/msolve_jll.jl/releases/download/msolve-v0.900.500+0/msolve.v0.900.500.x86_64-linux-gnu-march+avx512.tar.gz"
[[msolve]]
arch = "x86_64"
git-tree-sha1 = "f078b8a5cb0f35a897f0ed631a4381e3b492936f"
libc = "glibc"
march = "x86_64"
os = "linux"

    [[msolve.download]]
    sha256 = "14641236854a4d4b977bd4b90ca80b04cb4d81e4acc58aa3130d30b25661102f"
    url = "https://github.com/JuliaBinaryWrappers/msolve_jll.jl/releases/download/msolve-v0.900.500+0/msolve.v0.900.500.x86_64-linux-gnu-march+x86_64.tar.gz"
[[msolve]]
arch = "x86_64"
git-tree-sha1 = "16f8720eb059abc1228cbe00f4e4cc621d39ff39"
libc = "musl"
march = "avx"
os = "linux"

    [[msolve.download]]
    sha256 = "e9ddcec9c319eb9a9f1613f50bdbb82d088b8bc4deb0ac4d0df35a032bdb5332"
    url = "https://github.com/JuliaBinaryWrappers/msolve_jll.jl/releases/download/msolve-v0.900.500+0/msolve.v0.900.500.x86_64-linux-musl-march+avx.tar.gz"
[[msolve]]
arch = "x86_64"
git-tree-sha1 = "016b4a5556be219766a58bab0ea90847d7f148b4"
libc = "musl"
march = "avx2"
os = "linux"

    [[msolve.download]]
    sha256 = "27ca7e79200778624028cb50b85f79f2e8135409d26da02dee1ace7e4d84c4ec"
    url = "https://github.com/JuliaBinaryWrappers/msolve_jll.jl/releases/download/msolve-v0.900.500+0/msolve.v0.900.500.x86_64-linux-musl-march+avx2.tar.gz"
[[msolve]]
arch = "x86_64"
git-tree-sha1 = "b160132184163e36a11d7c0a97d4c5c7f2d69663"
libc = "musl"
march = "avx512"
os = "linux"

    [[msolve.download]]
    sha256 = "3328653db2838e4d534b31d2f7467519372fbc8a7b8c1a55bd6c45c58e17fae2"
    url = "https://github.com/JuliaBinaryWrappers/msolve_jll.jl/releases/download/msolve-v0.900.500+0/msolve.v0.900.500.x86_64-linux-musl-march+avx512.tar.gz"
[[msolve]]
arch = "x86_64"
git-tree-sha1 = "7a9dc9317f39286d3b34305d48141e92513c33ea"
libc = "musl"
march = "x86_64"
os = "linux"

    [[msolve.download]]
    sha256 = "18d2e721415a14f68c8339e12f8b5c5709b877007ae8ad09be9f6e6334fc86ac"
    url = "https://github.com/JuliaBinaryWrappers/msolve_jll.jl/releases/download/msolve-v0.900.500+0/msolve.v0.900.500.x86_64-linux-musl-march+x86_64.tar.gz"
[[msolve]]
arch = "x86_64"
git-tree-sha1 = "ccb884ad4bb13a7312ae5a85d75f60f5a0bf2235"
march = "avx"
os = "freebsd"

    [[msolve.download]]
    sha256 = "1d3a38749b13d7bc4660bd853d3ce591ab88f7bfbe9e3edba69d072db48a2446"
    url = "https://github.com/JuliaBinaryWrappers/msolve_jll.jl/releases/download/msolve-v0.900.500+0/msolve.v0.900.500.x86_64-unknown-freebsd-march+avx.tar.gz"
[[msolve]]
arch = "x86_64"
git-tree-sha1 = "b7d4758e2de19463562c133b064d3b07c822ec69"
march = "avx2"
os = "freebsd"

    [[msolve.download]]
    sha256 = "1a46ab6c3e5dece6a0bcf0d211bc8ccf0b6d32d0d15866ecd212ec32a8a145a7"
    url = "https://github.com/JuliaBinaryWrappers/msolve_jll.jl/releases/download/msolve-v0.900.500+0/msolve.v0.900.500.x86_64-unknown-freebsd-march+avx2.tar.gz"
[[msolve]]
arch = "x86_64"
git-tree-sha1 = "1632508efc995e1e9680d6f67decfe2fb440c384"
march = "avx512"
os = "freebsd"

    [[msolve.download]]
    sha256 = "1ae2f529294d93257ae6ca94f6f3a36c8cbdcec49c71b5df91a26bb32fbe4505"
    url = "https://github.com/JuliaBinaryWrappers/msolve_jll.jl/releases/download/msolve-v0.900.500+0/msolve.v0.900.500.x86_64-unknown-freebsd-march+avx512.tar.gz"
[[msolve]]
arch = "x86_64"
git-tree-sha1 = "efce98fb589fba4b7db961220ef110c7910723ee"
march = "x86_64"
os = "freebsd"

    [[msolve.download]]
    sha256 = "ce918f575663c6b36d8fe3b8cf236474109504f3849e8ec2c5251c13dc05798b"
    url = "https://github.com/JuliaBinaryWrappers/msolve_jll.jl/releases/download/msolve-v0.900.500+0/msolve.v0.900.500.x86_64-unknown-freebsd-march+x86_64.tar.gz"
