[[msolve]]
arch = "aarch64"
git-tree-sha1 = "6884c58b776b008cc2516c1d859863f7dbc78122"
march = "apple_m1"
os = "macos"

    [[msolve.download]]
    sha256 = "d3c028d6793ca6104bacb88086642d814635d7cf49d4456cec43bb4f36fd64ae"
    url = "https://github.com/JuliaBinaryWrappers/msolve_jll.jl/releases/download/msolve-v0.1000.1+0/msolve.v0.1000.1.aarch64-apple-darwin-march+apple_m1.tar.gz"
[[msolve]]
arch = "aarch64"
git-tree-sha1 = "9741d6b1770c7d38d949406b52dc52a47306bd52"
march = "armv8_0"
os = "macos"

    [[msolve.download]]
    sha256 = "572bcf82c8514b67cd988a737604d66e48f15a44a8829d87a435306df6b86cce"
    url = "https://github.com/JuliaBinaryWrappers/msolve_jll.jl/releases/download/msolve-v0.1000.1+0/msolve.v0.1000.1.aarch64-apple-darwin-march+armv8_0.tar.gz"
[[msolve]]
arch = "aarch64"
git-tree-sha1 = "0fea5cea0fd5eeffeeb53b489d31be866d600a85"
libc = "glibc"
march = "a64fx"
os = "linux"

    [[msolve.download]]
    sha256 = "208eb01c3088884467a354f492ea47b0035490f47c855442ed1f17d8d81dbf02"
    url = "https://github.com/JuliaBinaryWrappers/msolve_jll.jl/releases/download/msolve-v0.1000.1+0/msolve.v0.1000.1.aarch64-linux-gnu-march+a64fx.tar.gz"
[[msolve]]
arch = "aarch64"
git-tree-sha1 = "2ab2f6a661db6ce92eb20eaf1705003b46e797d2"
libc = "glibc"
march = "armv8_0"
os = "linux"

    [[msolve.download]]
    sha256 = "f4eab7fcc31386085ac24ad9a0224b81a07b35a018097fa259d17537829b3937"
    url = "https://github.com/JuliaBinaryWrappers/msolve_jll.jl/releases/download/msolve-v0.1000.1+0/msolve.v0.1000.1.aarch64-linux-gnu-march+armv8_0.tar.gz"
[[msolve]]
arch = "aarch64"
git-tree-sha1 = "01d5ca74b9a7c9184276d9a60f157ff606eddcb2"
libc = "glibc"
march = "armv8_1"
os = "linux"

    [[msolve.download]]
    sha256 = "3b1429c6b92efd5d6b39b1bf3db055fd68c00deb8e1f86fe2ce5565f981a89e6"
    url = "https://github.com/JuliaBinaryWrappers/msolve_jll.jl/releases/download/msolve-v0.1000.1+0/msolve.v0.1000.1.aarch64-linux-gnu-march+armv8_1.tar.gz"
[[msolve]]
arch = "aarch64"
git-tree-sha1 = "69afb4f419ea73b78d5a95e361aab6d481e9bd70"
libc = "glibc"
march = "armv8_2_crypto"
os = "linux"

    [[msolve.download]]
    sha256 = "ca75f522e03009b3138091b93f07268cb160c32fcee93414abfd57cbfa109da0"
    url = "https://github.com/JuliaBinaryWrappers/msolve_jll.jl/releases/download/msolve-v0.1000.1+0/msolve.v0.1000.1.aarch64-linux-gnu-march+armv8_2_crypto.tar.gz"
[[msolve]]
arch = "aarch64"
git-tree-sha1 = "4d845a036716e4de10a7096fdebbd170b45c6f56"
libc = "musl"
march = "armv8_0"
os = "linux"

    [[msolve.download]]
    sha256 = "654dc74a261f4059a5abd988ee194aeadb2637675c866757a1f3449e189ecad0"
    url = "https://github.com/JuliaBinaryWrappers/msolve_jll.jl/releases/download/msolve-v0.1000.1+0/msolve.v0.1000.1.aarch64-linux-musl-march+armv8_0.tar.gz"
[[msolve]]
arch = "aarch64"
git-tree-sha1 = "bf51e8074c874ecd6c2570ad6f7e33a160c69a88"
libc = "musl"
march = "armv8_1"
os = "linux"

    [[msolve.download]]
    sha256 = "ec2733b73474d53389dd254d5b193d1af736271f0b5517f4c9ff84d5f38a9012"
    url = "https://github.com/JuliaBinaryWrappers/msolve_jll.jl/releases/download/msolve-v0.1000.1+0/msolve.v0.1000.1.aarch64-linux-musl-march+armv8_1.tar.gz"
[[msolve]]
arch = "aarch64"
git-tree-sha1 = "596787c12c30eb8a1fea866b1e501691c5889e77"
libc = "musl"
march = "armv8_2_crypto"
os = "linux"

    [[msolve.download]]
    sha256 = "5e479328b47fa1e254e1b334641957139fcd1fe498d9a87aa317ed6ce42fcdf4"
    url = "https://github.com/JuliaBinaryWrappers/msolve_jll.jl/releases/download/msolve-v0.1000.1+0/msolve.v0.1000.1.aarch64-linux-musl-march+armv8_2_crypto.tar.gz"
[[msolve]]
arch = "aarch64"
git-tree-sha1 = "ab90edcaf9c0ffa4543e284811185872a78c30a8"
march = "armv8_0"
os = "freebsd"

    [[msolve.download]]
    sha256 = "6a0de7fe58588b673782996afd77de5009fba03a7890878b51e2588210c02be8"
    url = "https://github.com/JuliaBinaryWrappers/msolve_jll.jl/releases/download/msolve-v0.1000.1+0/msolve.v0.1000.1.aarch64-unknown-freebsd-march+armv8_0.tar.gz"
[[msolve]]
arch = "aarch64"
git-tree-sha1 = "9df2ee15324d47d2cad30c6831e682d202695d42"
march = "armv8_1"
os = "freebsd"

    [[msolve.download]]
    sha256 = "121714f0e7f2ea7ed50b86c04af9bf574f108d877fa62cc3c6e5e5b6aa576191"
    url = "https://github.com/JuliaBinaryWrappers/msolve_jll.jl/releases/download/msolve-v0.1000.1+0/msolve.v0.1000.1.aarch64-unknown-freebsd-march+armv8_1.tar.gz"
[[msolve]]
arch = "aarch64"
git-tree-sha1 = "d2ebb25359ae356d3756791560a55f8606799300"
march = "armv8_2_crypto"
os = "freebsd"

    [[msolve.download]]
    sha256 = "693f0819c704464cf8caf47e4646994ceec0003267607ea94c7bfdca89816040"
    url = "https://github.com/JuliaBinaryWrappers/msolve_jll.jl/releases/download/msolve-v0.1000.1+0/msolve.v0.1000.1.aarch64-unknown-freebsd-march+armv8_2_crypto.tar.gz"
[[msolve]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "55e5567eb0e76925ec29c7677e79cd3968a18c62"
libc = "glibc"
march = "arm1176jzfs"
os = "linux"

    [[msolve.download]]
    sha256 = "5bfe87e27d38d8aabb7e84713e13de17414a1bf8f497ac0a5f88746ed7848a2f"
    url = "https://github.com/JuliaBinaryWrappers/msolve_jll.jl/releases/download/msolve-v0.1000.1+0/msolve.v0.1000.1.armv6l-linux-gnueabihf-march+arm1176jzfs.tar.gz"
[[msolve]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "afdc27abb40cf949cb03948b0a6d81f7dcc7c774"
libc = "musl"
march = "arm1176jzfs"
os = "linux"

    [[msolve.download]]
    sha256 = "74b1d68291d452689f75084c8a1769d0b31356bf0e7419225c893e99737f4e24"
    url = "https://github.com/JuliaBinaryWrappers/msolve_jll.jl/releases/download/msolve-v0.1000.1+0/msolve.v0.1000.1.armv6l-linux-musleabihf-march+arm1176jzfs.tar.gz"
[[msolve]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "2addf4e28717fd372300541f62443b5386a0b0ce"
libc = "glibc"
march = "armv7l"
os = "linux"

    [[msolve.download]]
    sha256 = "618d5facba91157030d437e1084d251080db72da500a5ae2f51d9e56b0fe579c"
    url = "https://github.com/JuliaBinaryWrappers/msolve_jll.jl/releases/download/msolve-v0.1000.1+0/msolve.v0.1000.1.armv7l-linux-gnueabihf-march+armv7l.tar.gz"
[[msolve]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "9761907a674b638f100c5cb4984355452719a213"
libc = "glibc"
march = "neonvfpv4"
os = "linux"

    [[msolve.download]]
    sha256 = "806f97e64aa56262605c34cea9fd78d3584924d2d74a9a3e6ed58464b5e4d126"
    url = "https://github.com/JuliaBinaryWrappers/msolve_jll.jl/releases/download/msolve-v0.1000.1+0/msolve.v0.1000.1.armv7l-linux-gnueabihf-march+neonvfpv4.tar.gz"
[[msolve]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "c90478d5c683292d0364076b24825a111cb8dce0"
libc = "musl"
march = "armv7l"
os = "linux"

    [[msolve.download]]
    sha256 = "f9b524f10b262df07021f1da3ce12b7c0d43ad599b7bdf58a9e2eb96a7ed7bd7"
    url = "https://github.com/JuliaBinaryWrappers/msolve_jll.jl/releases/download/msolve-v0.1000.1+0/msolve.v0.1000.1.armv7l-linux-musleabihf-march+armv7l.tar.gz"
[[msolve]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "7c6876c6cdb305abb669980cb2a2dec912149fe1"
libc = "musl"
march = "neonvfpv4"
os = "linux"

    [[msolve.download]]
    sha256 = "c6ba11a69873dd729f180c819fa46fa86d80c2ed88acf679717b9fabbf945748"
    url = "https://github.com/JuliaBinaryWrappers/msolve_jll.jl/releases/download/msolve-v0.1000.1+0/msolve.v0.1000.1.armv7l-linux-musleabihf-march+neonvfpv4.tar.gz"
[[msolve]]
arch = "i686"
git-tree-sha1 = "1857717e142caf132c61604985054c671498e983"
libc = "glibc"
march = "pentium4"
os = "linux"

    [[msolve.download]]
    sha256 = "1648677b01895c4f3c865a3a4e5a1a291fac74cf54b3351a1f3823f63f027d4c"
    url = "https://github.com/JuliaBinaryWrappers/msolve_jll.jl/releases/download/msolve-v0.1000.1+0/msolve.v0.1000.1.i686-linux-gnu-march+pentium4.tar.gz"
[[msolve]]
arch = "i686"
git-tree-sha1 = "618cc9f5c270705269e1a4d15e3eeaaa87e0955b"
libc = "glibc"
march = "prescott"
os = "linux"

    [[msolve.download]]
    sha256 = "154b8c8bcf1f7bc28710007ceb3c0b97d3aafa0f3f032ce39a2c87110d6af3ad"
    url = "https://github.com/JuliaBinaryWrappers/msolve_jll.jl/releases/download/msolve-v0.1000.1+0/msolve.v0.1000.1.i686-linux-gnu-march+prescott.tar.gz"
[[msolve]]
arch = "i686"
git-tree-sha1 = "9f1477fd5796843c45480bd8f7b8e849f6431a42"
libc = "musl"
march = "pentium4"
os = "linux"

    [[msolve.download]]
    sha256 = "1fca133470c5b12cd537bde8f5bfcf65ed7fafc365267f73f96fabf5f4ae7144"
    url = "https://github.com/JuliaBinaryWrappers/msolve_jll.jl/releases/download/msolve-v0.1000.1+0/msolve.v0.1000.1.i686-linux-musl-march+pentium4.tar.gz"
[[msolve]]
arch = "i686"
git-tree-sha1 = "2a90604fc6926d349ad60208bd63237e8f5bbf35"
libc = "musl"
march = "prescott"
os = "linux"

    [[msolve.download]]
    sha256 = "f8d08f84e0b3f015264c37cbf8d1add47a50c0e56e995160cd27ea72de9b076f"
    url = "https://github.com/JuliaBinaryWrappers/msolve_jll.jl/releases/download/msolve-v0.1000.1+0/msolve.v0.1000.1.i686-linux-musl-march+prescott.tar.gz"
[[msolve]]
arch = "powerpc64le"
git-tree-sha1 = "2e4ce41f7c2daba61edb054867119b58e3a1c8ce"
libc = "glibc"
march = "power8"
os = "linux"

    [[msolve.download]]
    sha256 = "2c87f8101f5199c3ffbc6b3b5b7805a4c3c6ff81d25190964cae35e10847cc87"
    url = "https://github.com/JuliaBinaryWrappers/msolve_jll.jl/releases/download/msolve-v0.1000.1+0/msolve.v0.1000.1.powerpc64le-linux-gnu-march+power8.tar.gz"
[[msolve]]
arch = "riscv64"
git-tree-sha1 = "7ff3e47efcf772b02b62ffc48a073e3b4401baee"
libc = "glibc"
march = "riscv64"
os = "linux"

    [[msolve.download]]
    sha256 = "8483e8d172f61ada0662727c9005b6576209a4bedb02f7ec912735c48cc185c2"
    url = "https://github.com/JuliaBinaryWrappers/msolve_jll.jl/releases/download/msolve-v0.1000.1+0/msolve.v0.1000.1.riscv64-linux-gnu-march+riscv64.tar.gz"
[[msolve]]
arch = "x86_64"
git-tree-sha1 = "39a106eae029ee7f90fa0d3d143af980de89709f"
march = "avx"
os = "macos"

    [[msolve.download]]
    sha256 = "757617492ccdcd5adf71e53e920af5cc45d496729fa9d9c79cfeb92663e3f21d"
    url = "https://github.com/JuliaBinaryWrappers/msolve_jll.jl/releases/download/msolve-v0.1000.1+0/msolve.v0.1000.1.x86_64-apple-darwin-march+avx.tar.gz"
[[msolve]]
arch = "x86_64"
git-tree-sha1 = "c38be0606f188e7f045926a0556a9d6f5223c2c4"
march = "avx2"
os = "macos"

    [[msolve.download]]
    sha256 = "e6d3b90ba1a9275b8ed2733410d2e530d453d7f311a59590585cbdf2c9273e8b"
    url = "https://github.com/JuliaBinaryWrappers/msolve_jll.jl/releases/download/msolve-v0.1000.1+0/msolve.v0.1000.1.x86_64-apple-darwin-march+avx2.tar.gz"
[[msolve]]
arch = "x86_64"
git-tree-sha1 = "710a3c6a3550eb8c6a68cb52205dfb4b5524a2d4"
march = "avx512"
os = "macos"

    [[msolve.download]]
    sha256 = "79491bb1d7b74707a16512f70d7c7b48196b1f588c671238611070ebe5a2697d"
    url = "https://github.com/JuliaBinaryWrappers/msolve_jll.jl/releases/download/msolve-v0.1000.1+0/msolve.v0.1000.1.x86_64-apple-darwin-march+avx512.tar.gz"
[[msolve]]
arch = "x86_64"
git-tree-sha1 = "5fcef033ffb0d83be028bcfa594e92ac925f35b2"
march = "x86_64"
os = "macos"

    [[msolve.download]]
    sha256 = "ac07f0a18368056a9c43205d68fbb96f1b2de34fa4581ec7750dd5c332d48317"
    url = "https://github.com/JuliaBinaryWrappers/msolve_jll.jl/releases/download/msolve-v0.1000.1+0/msolve.v0.1000.1.x86_64-apple-darwin-march+x86_64.tar.gz"
[[msolve]]
arch = "x86_64"
git-tree-sha1 = "ad228ed412d485e765e3792fdf77429117ca020c"
libc = "glibc"
march = "avx"
os = "linux"

    [[msolve.download]]
    sha256 = "ddf883c124e423bfc522c590e8ed377f08a9295ee41f6d810ac847f479b6adbd"
    url = "https://github.com/JuliaBinaryWrappers/msolve_jll.jl/releases/download/msolve-v0.1000.1+0/msolve.v0.1000.1.x86_64-linux-gnu-march+avx.tar.gz"
[[msolve]]
arch = "x86_64"
git-tree-sha1 = "67fbba61b14a22bf41128b09b51d88c6c29919bd"
libc = "glibc"
march = "avx2"
os = "linux"

    [[msolve.download]]
    sha256 = "48df37ed1c2d71cae9a1bd8f003c33c0004f9e84b770f86904a18cf606d8c4a5"
    url = "https://github.com/JuliaBinaryWrappers/msolve_jll.jl/releases/download/msolve-v0.1000.1+0/msolve.v0.1000.1.x86_64-linux-gnu-march+avx2.tar.gz"
[[msolve]]
arch = "x86_64"
git-tree-sha1 = "25085afb399f5dfce213dc0558e7e2aa2eb5efe6"
libc = "glibc"
march = "avx512"
os = "linux"

    [[msolve.download]]
    sha256 = "e6733b8f9e3f0048d566d86ae4717db36a60db043379f68665a1abdeaae12896"
    url = "https://github.com/JuliaBinaryWrappers/msolve_jll.jl/releases/download/msolve-v0.1000.1+0/msolve.v0.1000.1.x86_64-linux-gnu-march+avx512.tar.gz"
[[msolve]]
arch = "x86_64"
git-tree-sha1 = "509279c8eae9d0176e80e90eb39ebe12f715d479"
libc = "glibc"
march = "x86_64"
os = "linux"

    [[msolve.download]]
    sha256 = "39c4ecfacdc7553b2df9e9ae042339412c00bd41f68fe1c29756943d48d8c0aa"
    url = "https://github.com/JuliaBinaryWrappers/msolve_jll.jl/releases/download/msolve-v0.1000.1+0/msolve.v0.1000.1.x86_64-linux-gnu-march+x86_64.tar.gz"
[[msolve]]
arch = "x86_64"
git-tree-sha1 = "8e449e24079b971ada688ffe612ce52bc630e9e5"
libc = "musl"
march = "avx"
os = "linux"

    [[msolve.download]]
    sha256 = "6f4f9fe6e9781d7ae05cd9cdb4e86ab2212e9b5eb492e9ceaed1ba564eedec03"
    url = "https://github.com/JuliaBinaryWrappers/msolve_jll.jl/releases/download/msolve-v0.1000.1+0/msolve.v0.1000.1.x86_64-linux-musl-march+avx.tar.gz"
[[msolve]]
arch = "x86_64"
git-tree-sha1 = "c2ac6a3c6613cd2210c073071cb2a87240281e0b"
libc = "musl"
march = "avx2"
os = "linux"

    [[msolve.download]]
    sha256 = "c531359f9dce7099add04cedbd1a8077e4dc722bd53236a0271e53cf9882cc97"
    url = "https://github.com/JuliaBinaryWrappers/msolve_jll.jl/releases/download/msolve-v0.1000.1+0/msolve.v0.1000.1.x86_64-linux-musl-march+avx2.tar.gz"
[[msolve]]
arch = "x86_64"
git-tree-sha1 = "f6e2b9e9ec2063c4d46a4a2400ee3e5ce2a4d396"
libc = "musl"
march = "avx512"
os = "linux"

    [[msolve.download]]
    sha256 = "afe944df49889224590b310a43a4dfd1b1ed56480680947c6b8eec497211f428"
    url = "https://github.com/JuliaBinaryWrappers/msolve_jll.jl/releases/download/msolve-v0.1000.1+0/msolve.v0.1000.1.x86_64-linux-musl-march+avx512.tar.gz"
[[msolve]]
arch = "x86_64"
git-tree-sha1 = "09d9f1b94594e9b556d0be18b1779d6be0c68e13"
libc = "musl"
march = "x86_64"
os = "linux"

    [[msolve.download]]
    sha256 = "0473ecd1a7a4323b54539488f8b9f324a7cbd103f92967dc7b597212e7e8b042"
    url = "https://github.com/JuliaBinaryWrappers/msolve_jll.jl/releases/download/msolve-v0.1000.1+0/msolve.v0.1000.1.x86_64-linux-musl-march+x86_64.tar.gz"
[[msolve]]
arch = "x86_64"
git-tree-sha1 = "02c875444ae4ac7dcaa6b004d3149244a7ecd837"
march = "avx"
os = "freebsd"

    [[msolve.download]]
    sha256 = "c2c83031826b6609bec9c9bf2e1d8ba5b6f77915a0dcd58476fee21e38e78e79"
    url = "https://github.com/JuliaBinaryWrappers/msolve_jll.jl/releases/download/msolve-v0.1000.1+0/msolve.v0.1000.1.x86_64-unknown-freebsd-march+avx.tar.gz"
[[msolve]]
arch = "x86_64"
git-tree-sha1 = "9ae59b7b72686211c2756bfe8f1761d901c4f36b"
march = "avx2"
os = "freebsd"

    [[msolve.download]]
    sha256 = "cb6bef9684b9208c8a4255af88432579f9e56b0268c86e976abf35a269fdcd07"
    url = "https://github.com/JuliaBinaryWrappers/msolve_jll.jl/releases/download/msolve-v0.1000.1+0/msolve.v0.1000.1.x86_64-unknown-freebsd-march+avx2.tar.gz"
[[msolve]]
arch = "x86_64"
git-tree-sha1 = "51ceea588af0efa89377a767046d7e08031ccb41"
march = "avx512"
os = "freebsd"

    [[msolve.download]]
    sha256 = "30df70ae704b9dc44c070979fe23fd1f8763fca3e4ea05e954cc62c4ef55a3c5"
    url = "https://github.com/JuliaBinaryWrappers/msolve_jll.jl/releases/download/msolve-v0.1000.1+0/msolve.v0.1000.1.x86_64-unknown-freebsd-march+avx512.tar.gz"
[[msolve]]
arch = "x86_64"
git-tree-sha1 = "7b669fc4d553d4e0afd91de62d9e0e4ac144fdd0"
march = "x86_64"
os = "freebsd"

    [[msolve.download]]
    sha256 = "0fbec0c91cbbb186ddcb97a98c7b319c7d8cc2548748dba1afed946f0f20bc73"
    url = "https://github.com/JuliaBinaryWrappers/msolve_jll.jl/releases/download/msolve-v0.1000.1+0/msolve.v0.1000.1.x86_64-unknown-freebsd-march+x86_64.tar.gz"
